version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    volumes:
      - ./.env.development:/app/.env.development
      - ./credentials.dev.json:/app/credentials.dev.json 