version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    volumes:
      - ./.env.production:/app/.env.production
      - ./credentials.prod.json:/app/credentials.prod.json 